apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: keda-spinapp
spec:
  image: ghcr.io/spinkube/spin-operator/cpu-load-gen:20240311-163328-g1121986
  executor: containerd-shim-spin
  enableAutoscaling: true
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 600Mi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-autoscaler
spec:
  scaleTargetRef:
    name: keda-spinapp
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"